CREATE TABLE IF NOT EXISTS votes
(
  id            BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  candidate_id  BIGINT UNSIGNED NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  user_rights_id BIGINT UNSIGNED NOT NULL UNIQUE REFERENCES user_rights(id) ON DELETE CASCADE,
  election_id   BIGINT UNSIGNED NOT NULL REFERENCES elections(id) ON DELETE CASCADE,
  
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);